#!/bin/bash

delete_files() {
	MOVIES=$(jq -r '.movies | join(",")' "$JSON_FILE")
	MUSICS=$(jq -r '.musics | join(",")' "$JSON_FILE")
	BOOKS=$(jq -r '.books | join(",")' "$JSON_FILE")
	IMAGES=$(jq -r '.images | join(",")' "$JSON_FILE")

	# check that variable is not empty, then remove

	if [ -n "$MOVIES" ]; then
		if [[ $variable == *,* ]]; then
			eval rm -rf "$TARGET_PATH/movies/{$MOVIES}"
		else
			eval rm -rf "$TARGET_PATH/movies/$MOVIES"
		fi
	fi

	if [ -n "$MUSICS" ]; then
		if [[ $variable == *,* ]]; then
			eval rm "$TARGET_PATH/musics/{$MUSICS}.mp3"
		else
			eval rm -rf "$TARGET_PATH/musics/$MUSICS.mp3"
		fi
	fi

	if [ -n "$BOOKS" ]; then
		if [[ $variable == *,* ]]; then
			eval rm "$TARGET_PATH/books/{$BOOKS}.pdf"
		else
			eval rm -rf "$TARGET_PATH/books/$BOOKS.pdf"
		fi
	fi

	if [ -n "$IMAGES" ]; then
		if [[ $variable == *,* ]]; then
			eval rm "$TARGET_PATH/images/movies/{$IMAGES}.jpg"
		else
			eval rm -rf "$TARGET_PATH/images/movies/$IMAGES.jpg"
		fi
	fi
}
