#!/bin/bash

dump() {
	echo "Stopping service $SERVICE_NAME..."
	if ! systemctl stop "$SERVICE_NAME"; then
		error_exit "Failed to stop $SERVICE_NAME"
	fi

	echo "Restoring database $DB_NAME from $SQL_DUMP_FILE..."
	if ! psql -U postgres -d postgres -c "DROP DATABASE IF EXISTS $DB_NAME"; then
		error_exit "Failed to drop database $DB_NAME"
	fi

	if ! psql -U postgres -d postgres -c "CREATE DATABASE $DB_NAME"; then
		error_exit "Failed to create database $DB_NAME"
	fi

	if ! psql -U postgres -d "$DB_NAME" -f "$SQL_DUMP_FILE" > /dev/null; then
		error_exit "Failed to restore database $DB_NAME from $SQL_DUMP_FILE"
	fi

	echo "Starting service $SERVICE_NAME..."
	if ! systemctl start "$SERVICE_NAME"; then
		error_exit "Failed to start $SERVICE_NAME"
	fi
}
