#!/bin/bash

DEFAULT_DEVICE="/dev/sdb1"

DEVICE="${1:-$DEFAULT_DEVICE}"
SOURCE_PATH="/home/rado/media"
TARGET_PATH="/var/www/media/uploads"
SERVICE_NAME="media.service"
DB_NAME="media"
SQL_DUMP_FILE="$SOURCE_PATH/changes/dump.sql"
JSON_FILE="$SOURCE_PATH/changes/delete_files.json"

# Function to handle errors
error_exit() {
    echo -e "\nError: $1" >&2
    exit 1
}

source ./cp_files
source ./dump
source ./delete_files

echo -e "\nMounting device $DEVICE"

if ! mount $DEVICE $SOURCE_PATH; then
    error_exit "Couldn't mount $DEVICE"
fi

echo -e "$DEVICE has been mounted\n"

cp_files
dump
delete_files

echo -e "\nSuccessfully done"
echo -e "\nUnmounting $DEVICE..."
umount $SOURCE_PATH
echo "Done"
