#!/bin/bash

DEVICE="/dev/sdb1"
# Use the provided argument or default to the default path
SOURCE_PATH="/home/rado/media"
TARGET_PATH="/var/www/media/uploads"
SERVICE_NAME="media.service"
DB_NAME="media"
SQL_DUMP_FILE="$SOURCE_PATH/changes/dump.sql"
JSON_FILE="$SOURCE_PATH/changes/delete_files.json"

# Function to handle errors
error_exit() {
    echo "Error: $1" >&2
    exit 1
}

source ./cp_files
source ./dump
source ./delete_files

echo "Mounting device $DEVICE"
mount $DEVICE $SOURCE_PATH
echo "$DEVICE has been mounted"

cp_files
dump
delete_files

echo "Successfully done"
